api/urls.py
from django.urls import path

from .views.contact_view import ContactEnrollView

app_name = "api"

urlpatterns = [
    path("contact", ContactEnrollView.as_view(), name="contact-enroll"),
]

core/urls.py
from django.urls import path

from core.views.register_view import register
from core.views.views import (
    home, login_view,
    logout_view, account,
    dashboard, about,
    search_results,
    running,
    software_development,
    mathematics,
    contact,
    blog,
)

app_name = 'core'

urlpatterns = [
    path('', home, name='home'),
    path("about/", about, name='about'),
    path('accounts/login/', login_view, name='login'),
    path('accounts/logout', logout_view, name='logout'),
    path('accounts/register', register, name='register'),
    path('accounts/<int:pk>/', account, name='accounts'),
    path('blog/', blog, name='blog'),
    path('contact/', contact, name='contact'),
    path("dashboard/", dashboard, name='dashboard'),
    path("dashboard/", dashboard, name='dashboard'),
    path("mathematics/", mathematics, name='mathematics'),
    path("running/", running, name='running'),
    path("software/", software_development, name='software-development'),
    path("search/", search_results, name='-search'),
]

dumpstR/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include("api.urls")),
    path('', include("core.urls")),

]

templates/base.html
{% include "header.html" %}
{% block body %}
{% endblock body %}
{% include "footer.html" %}

templates/footer.html
{% load static %}
<footer class="footer">
    <section class="mb-4 footer-section ">
        <!-- Twitter -->
        <a
            class="btn btn-primary btn-floating m-1"
            style="background-color: #55acee;"
            href="https://twitter.com/chessmathematic"
            role="button"
        ><i class="fab fa-twitter"></i
        ></a>

        <!-- Linkedin -->
        <a
            class="btn btn-primary btn-floating m-1"
            style="background-color: #0082ca;"
            href="https://www.linkedin.com/in/kalenshi"
            role="button"
        ><i class="fab fa-linkedin-in"></i
        ></a>
        <!-- Github -->
        <a
            class="btn btn-primary btn-floating m-1"
            style="background-color: #333333;"
            href="https://github.com/kalenshi"
            role="button"
        ><i class="fab fa-github"></i
        ></a>
    </section>
</footer>
</div>
<script src="{% static 'js/app.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.js' %}"></script>
</body>
</html>

templates/header.html
<!doctype html>
{% load static %}
<html class="no-js" lang="">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{title|default_if_none:"dumpstR"}}</title>
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
          integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/nav-styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <meta name="description" content="">

    <meta property="og:title" content="">
    <meta property="og:type" content="">
    <meta property="og:url" content="">
    <meta property="og:image" content="">

    <link rel="icon" href="{% static 'img/favicon.ico' %}" sizes="any">
    <link rel="icon" href="{% static 'img/icon.svg' %}" type="image/svg+xml">
    <link rel="apple-touch-icon" href="{% static 'img/icon.png' %}">

    <!--  <link rel="manifest" href="site.webmanifest">-->
    <meta name="theme-color" content="#fafafa">
</head>

<body>
<div class="pagewrapper">
    <div class="header-div">
        {% include "navbar.html" %}
        <div class="message-div">
            {% if messages %}

            {% for message in messages %}
            <div class="alert alert-{{message.tags}} centered alert-dismissible fade show"
                 role="alert">
                <strong>{{message}}</strong>
                <button type="button" class="btn-close" data-bs-dismiss="alert"
                        aria-label="Close"></button>
            </div>
            {% endfor %}
            {% endif %}
        </div>
    </div>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'core:home' %}">dumpstR</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            {% with url_name=request.resolver_match.url_name %}
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link {% if url_name == 'link' %}active{% endif %}"
                       href="{% url 'core:blog' %}">Blog</a>
                </li>
                <li  class="nav-item">
                    <a class="nav-link {% if url_name == 'link' %}active{% endif %}"
                       href="{% url 'core:contact' %}">Contact</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if url_name == 'about' %}active{% endif %}"
                       href="{% url 'core:about' %}">About</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Features
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'core:running' %}">Running</a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="{% url 'core:software-development' %}">Software
                            Development</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item"
                               href="{% url 'core:mathematics' %}">Mathematics</a></li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if url_name == 'dashboard' %}active{% endif %}"
                       href="{% url 'core:dashboard' %}"
                       tabindex="-1">DashBoard</a>
                </li>

            </ul>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'core:logout' %}">
                        Logout
                    </a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown2" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Account
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item"
                               href="{% url 'core:accounts' pk=request.user.id%}">Profile</a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Some Feature
                        </a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item"
                               href="#">Another Feature</a></li>
                    </ul>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link {% if url_name == 'login' %}active{% endif %}"
                       href="{% url 'core:login' %}">
                        Login
                    </a>
                </li>
                <li class="nav-item {% if url_name == 'register' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'core:register' %}">
                        Register
                    </a>
                </li>
                {% endif %}
            </ul>
            {% endwith %}
            <form class="d-flex">
                <input class="form-control me-2" type="search" placeholder="Search"
                       aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>